### ISSUE TITLE
Producción: Carga no se detiene en crear artículo

### ISSUE THREAD

**Issue by Kyostenas** [RafaelAngelRamirez/control-de-produccion-GUI#22]
Al crear un nuevo artículo o hacerlo erróneamente, ocurre lo siguiente:
![image](https://user-images.githubusercontent.com/57164866/84167933-740d2680-aa3c-11ea-979d-d388e1cc0abd.png)
En este caso el artículo se creo erróneamente al no poner un código de localización único, pero también ocurre al hacerlo correctamente.

**Comment by RafaelAngelRamirez** [comment]
Cerrazón adelantada por qué usamos git flow. Pero no me gusto usar git flow. Perdemos el chow de los pull request que cierran issues
