### ISSUE TITLE
Arreglar detalle de usuarios

### ISSUE THREAD

**Issue by RafaelAngelRamirez** [RafaelAngelRamirez/control-de-produccion-GUI#3]
Arreglar el detalle de usuarios para que sea congruente con la estructura de asignación de permisos de usuario-crear-modificar.component.

Actualmente tiene esto:

![image](https://user-images.githubusercontent.com/27775245/84055382-5d9e9680-a97a-11ea-991a-9e8c1734c34e.png)

Debe parecerse a esto. 

![image](https://user-images.githubusercontent.com/27775245/84055431-6db67600-a97a-11ea-8a88-b98f214418f4.png)

**Comment by Kyostenas** [comment]
De momento luce así:
![image](https://user-images.githubusercontent.com/57164866/84165227-12978880-aa39-11ea-942a-b6f9bf7b0de7.png)

**Comment by RafaelAngelRamirez** [comment]
https://github.com/RafaelAngelRamirez/control-de-produccion-GUI/pull/21
