### ISSUE TITLE
Cada articulo (produccion) debe definirse como consumible o materia prima desde el principio

### ISSUE THREAD

**Issue by RafaelAngelRamirez** [RafaelAngelRamirez/control-de-produccion-GUI#7]
Cuando se cree el articulo debemos de darle opción a escoger y si no se escoge nada, por defecto que sea materia prima:

- [x] Crear select con opcion `Materia prima` y `Consumible`
- [x] Modificar formulario para que acepte estas dos opciones es`tipoDeProducto`
- [x] Que el select cargue por defecto 'Materia prima` 
- [x] Modificar modelo para que coincida con tipoDeProducto: 'MATERIA PRIMA | CONSUMIBLE'`
- [x] Terminar [este issue del api](https://github.com/RafaelAngelRamirez/control-de-produccion-API/issues/7)
- [x] Crear un nuevo issue para modificar las requisiciones al terminar este trabajo

Notas
---
Los `value='MATERIA PRIMA'` y `value='CONSUMIBLE'` deben ser en mayusculas, mientras que los datos para mostrar deben ser en solo la primera en mayusculas.

**Comment by Kyostenas** [comment]
[Issue para las requisisiciónes](https://github.com/RafaelAngelRamirez/control-de-produccion-GUI/issues/18)
