### ISSUE TITLE
Articulos debe tener imagenes para identificacion

### ISSUE THREAD

**Issue by RafaelAngelRamirez** [RafaelAngelRamirez/control-de-produccion-GUI#8]
Fichero service
================
```
Fecha de redacción:  mar 30 jun 2020 10:37:41
Fecha de término: pendiente
```

Por hacer
---------

- [x]  Agregar carga de imágenes con opción de eliminar en el modal
- [x]  Crear fichero service
- [x]  Crear fichero route
	- [x]  Hacer CRUD (sin update)
- [x]  Crear archivo de esquema para imágenes
- [ ] Que las imágenes huérfanas se registren con un botón

Descripción de tareas
---------------------

### Modal
- [x] Que cargue imágenes en caso de haber
- [x] Que se puedan eliminar en caso de ser cierto el primer paso
- [x] Que aparezca una x sobre cada imágen si la hay
- [ ] Definir nuevos permisos (definidos en los metodos http)
	- [ ] Si tiene permiso de cargar se muestra botón de modal
	- [ ] Si tiene permisos de eliminar id se muestra botón de eliminar imágen

### Fichero service

- Crear funciones

	- [x] `upload() {}`
	- [x] `findAll() {}`
	- [x] `finById() {}`
	- [x] `findByTerm() {}`
	- [x] `delete() {}`

### Imágenes route

Métodos por añadir

- post- /
`fichero:cargar`
- get- /buscar/todo
`fichero:buscar:todo`
- get- /buscar/id/:id
`fichero:buscar:id`
- get- /buscar/termino/termino
`fichero:buscar:termino`
- delete- /id/:id
`fichero:eliminar:id`

### Esquema

- `nombre`
- `nombreMostrar`
- `nombreArchivo`
- `path`
- `size`
- `tipo` (Imágen, documento)
- `descripciónDeFichero`

**Comment by Kyostenas** [comment]
Fichero service
================
```
Fecha de redacción:  mar 30 jun 2020 10:37:41
Fecha de término: pendiente
```

Por hacer
---------

- [ ]  Agregar carga de imágenes con opción de eliminar en el modal
- [ ]  Crear fichero service
- [ ]  Crear fichero route
	- [ ]  Hacer CRUD (sin update)
- [ ]  Crear archivo de esquema para imágenes

Descripción de tareas
---------------------

### Modal
- [ ] Que cargue imágenes en caso de haber
- [ ] Que se puedan eliminar en caso de ser cierto el primer paso
- [ ] Que aparezca una x sobre cada imágen si la hay
- [ ] Definir nuevos permisos (definidos en los metodos http)
	- [ ] Si tiene permiso de cargar se muestra botón de modal
	- [ ] Si tiene permisos de eliminar id se muestra botón de eliminar imágen

### Fichero service

- Crear funciones

	- [ ] `upload() {}`
	- [ ] `findAll() {}`
	- [ ] `finById() {}`
	- [ ] `findByTerm() {}`
	- [ ] `delete() {}`

### Imágenes route

Métodos por añadir

- post- /
`fichero:cargar`
- get- /buscar/todo
`fichero:buscar:todo`
- get- /buscar/id/:id
`fichero:buscar:id`
- get- /buscar/termino/termino
`fichero:buscar:termino`
- delete- /id/:id
`fichero:eliminar:id`

### Esquema

- `nombre`
- `nombreMostrar`
- `nombreArchivo`
- `tipo` (Imágen, documento)
- `descripciónDeFichero`

**Comment by Kyostenas** [comment]
Repositorio de la [librería](https://github.com/Kyostenas/Carga-de-ficheros)
